# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('citation', models.CharField(max_length=255)),
                ('consequence_details', models.TextField()),
                ('duration_desc', models.TextField()),
                ('state', models.CharField(choices=[('---', 'Choose a State'), ('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington, D.C.'), ('DE', 'Delaware'), ('FED', 'Federal'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='---', max_length=3)),
                ('duration', models.CharField(choices=[('---', 'Choose a Consequence Duration'), ('none', 'None'), ('bkg', 'Background Check/General Relief'), ('perm', 'Permanent/Unspecified'), ('spec', 'Specific Term'), ('cond', 'Conditional')], default='---', max_length=5)),
                ('offense_cat', multiselectfield.db.fields.MultiSelectField(choices=[('---', 'Choose a Category'), ('corruption', 'Public corruption offenses'), ('misdem', 'Any misdemeanor'), ('moral', 'Crime of moral turpitude'), ('child_supp', 'Child Support offenses'), ('driving', 'Motor vehicle offenses'), ('drugs', 'Controlled substances offenses'), ('sex', 'Sex offenses'), ('violence', 'Crimes of violence, including "person offenses"'), ('rec_license', 'Recreational license offenses'), ('fraud', 'Crimes involving fraud, dishonesty, misrepresentation or money-laundering'), ('any', 'Any offense (including felony, misdemeanor, and lesser offense)'), ('felony', 'Any felony'), ('weapons', 'Weapons offenses'), ('misc', 'Other')], default='---', max_length=15)),
                ('consequence_cat', multiselectfield.db.fields.MultiSelectField(choices=[('---', 'Choose a Category'), ('edu', 'Education'), ('family', 'Family/domestic rights'), ('govnt_bens', 'Government benefits'), ('govnt_contract', 'Government contracting and program participation'), ('govnt_loans', 'Government loans and grants'), ('housing', 'Housing'), ('jobs', 'Employment'), ('judicial', 'Judicial Rights'), ('prof_lic', 'Occupational and professional license and certification'), ('relief', 'General Relief Provision'), ('registration_lims', 'Registration, notification, and residency restrictions'), ('rec_weapons_lic', 'Recreational license, including firearms'), ('business_lic', 'Business license and other property rights'), ('driving_lic', 'Motor vehicle licensure'), ('voting', 'Political and civic participation')], default='---', max_length=20)),
                ('consequence_type', multiselectfield.db.fields.MultiSelectField(choices=[('---', 'Choose some consequence types')], default='---', max_length=5)),
            ],
        ),
    ]
