# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crime_type', models.CharField(choices=[('fel', 'Felony'), ('misd', 'Misdemeanor'), ('viol', 'Violation'), ('---', 'Choose a Crime Type')], default='---', max_length=40)),
                ('crime_class', models.CharField(choices=[('---', 'Choose a Class of Crime'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F')], default='---', max_length=5)),
                ('sex_offense', models.BooleanField(default=False)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
