# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryOffense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='crime',
            name='state',
            field=models.CharField(default='---', max_length=255),
        ),
    ]
