# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_auto_20170212_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='state',
            field=models.CharField(default='---', max_length=2),
        ),
    ]
