# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0004_auto_20170215_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequence',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
